name: Publish Packages to npm
on:
  push:
    branches: [main]
concurrency: Sync Packages to Public Repo-refs/heads/main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run packages:build
      - run: npm run packages:test
      - uses: changesets/action@v1
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiIteEl4TmlYeDdxZUpCQUYxRUxIQ1lzRGI1c3RWVGVobGE4aXdxR1VneUJlZXRzMEtRX18xMk1vIiwiZXhwIjoxNzg3MzQ5MTY2LCJpYXQiOjE3ODczNDU1NjYsImlzcyI6ImdpdGh1YiIsImp0aSI6Ijk4MjE1ZjY0LTVkNmMtNGZjMC04NDAzLTVhODJhNWRjMGYyNyIsInZlciI6M30.CwlAI0jIkMLj6PZuW_TNxsnTNbZap3W2lKlsgFAXBxcYzCTLJ18GqQDpRgXsAa1ODaArwaer9VfslJL0auOSzg
          NPM_CONFIG_PROVENANCE: true
