name: Publish Packages to npm
on:
  push:
    branches: [main]
concurrency: Sync Packages to Public Repo-refs/heads/main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run packages:build
      - run: npm run packages:test
      - uses: changesets/action@v1
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiJSMzVtSjZsNk1EdFBnZnRCWFgyN1BPRTZZVUdrS25WeGRBRV96ZHRPdkFXa1lrM05JclZwUzZjIiwiZXhwIjoxNzg3Mzc5MDgzLCJpYXQiOjE3ODczNzU0ODMsImlzcyI6ImdpdGh1YiIsImp0aSI6IjJmYTNjOGIwLTA3NGItNDZhYi04MWFlLWEzYTJlZTYxZDE1YyIsInZlciI6M30.gyk_Usonm8ls62inDD_Wcv7HIeor5KZ9dyFVHZUs4fvuHVzbNFgdZM2gJhS44e0ic8VMW0T0oBC_J-qoUV13fw
          NPM_CONFIG_PROVENANCE: true
