name: Publish Packages to npm
on:
  push:
    branches: [main]
concurrency: Sync Packages to Public Repo-refs/heads/main
jobs:
  release:
    name: Release
    runs-on: sotatek-dev-self-hosted
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run packages:build
      - run: npm run packages:test
      - uses: changesets/action@v1
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiJNYm9EamhjS0xTN2tJUWFaaUFQSWpBV2hFQVVKSUR2bXNUUTRPa0xMNW5mb0p3d0I3QVdrNDJJIiwiZXhwIjoxNzg3Mzg4NTE5LCJpYXQiOjE3ODczODQ5MTksImlzcyI6ImdpdGh1YiIsImp0aSI6ImQ5Mjc2NTI0LWQ0MDYtNDBiMC05Yjk0LWI5OTUwMWQ0M2I2OSIsInZlciI6M30.atr3rh4aP4uKmlT2ciZb7CxpsaNAoYhbPo1Ap7U0Vtn12rc3f_L3HYGiBSYG4SPnklomUItxZrMtQjCMI5UyOg
          NPM_CONFIG_PROVENANCE: true
